name: hammerspace-monitoring
services:
  init-dashboards:
    image: curlimages/curl:latest
    container_name: init-dashboards
    volumes:
      - ./grafana/dashboards:/dashboards
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        set -e
        mkdir -p /dashboards
        # Download dashboards from Hammerspace GitHub
        curl -L https://raw.githubusercontent.com/hammerspace-me/monitoring/main/dashboards/HammerspaceFileMobility-5.1.json -o /dashboards/HammerspaceFileMobility-5.1.json
        curl -L https://raw.githubusercontent.com/hammerspace-me/monitoring/main/dashboards/HammerspaceFilesystemReplication-5.1.json -o /dashboards/HammerspaceFilesystemReplication-5.1.json
        curl -L https://raw.githubusercontent.com/hammerspace-me/monitoring/main/dashboards/HammerspaceFilesystemStats-5.1.json -o /dashboards/HammerspaceFilesystemStats-5.1.json
        curl -L https://raw.githubusercontent.com/hammerspace-me/monitoring/main/dashboards/HammerspaceObjectMobility-5.1.json -o /dashboards/HammerspaceObjectMobility-5.1.json
        curl -L https://raw.githubusercontent.com/hammerspace-me/monitoring/main/dashboards/HammerspaceProtocolStats-5.1.json -o /dashboards/HammerspaceProtocolStats-5.1.json
        echo "Downloaded all dashboards successfully"
    networks:
      - hs-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - thor2_prometheus_data:/prometheus
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - hs-network
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
      - init-dashboards
    ports:
      - "3000:3000"
    volumes:
      - thor2_grafana_data:/var/lib/grafana
      - ./grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      # Simplified volume mount - mount the entire dashboards directory
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin!
      - PROMETHEUS_UID=DS_PROMETHEUS
    networks:
      - hs-network

volumes:
  thor2_prometheus_data:
  thor2_grafana_data:

networks:
  hs-network:
    driver: bridge