name: hammerspace-monitoring
services:
  init-dashboards:
    image: curlimages/curl:8.7.1
    container_name: init-dashboards
    volumes:
      - ./grafana/dashboards:/dashboards
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        set -e
        mkdir -p /dashboards
        # Download dashboards from Hammerspace GitHub
        curl -L https://raw.githubusercontent.com/hammer-space/hammerspace-grafana-dashboards/refs/heads/main/5.1/hammerspace_file_mobility.json -o /dashboards/hammerspace_file_mobility.json
        curl -L https://raw.githubusercontent.com/hammer-space/hammerspace-grafana-dashboards/refs/heads/main/5.1/hammerspace_filesystem_stats.json -o /dashboards/hammerspace_filesystem_stats.json        
        curl -L https://raw.githubusercontent.com/hammer-space/hammerspace-grafana-dashboards/refs/heads/main/5.1/hammerspace_object_mobility.json -o /dashboards/hammerspace_object_mobility.json
        curl -L https://raw.githubusercontent.com/hammer-space/hammerspace-grafana-dashboards/refs/heads/main/5.1/hammerspace_protocol_stats.json -o /dashboards/hammerspace_protocol_stats.json
        curl -L https://raw.githubusercontent.com/hammer-space/hammerspace-grafana-dashboards/refs/heads/main/5.1/hammerspace_replication.json -o /dashboards/hammerspace_replication.json
    networks:
      - hs-network

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - thor2_prometheus_data:/prometheus
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - hs-network
    
  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
      - init-dashboards
    ports:
      - "3000:3000"
    volumes:
      - thor2_grafana_data:/var/lib/grafana
      - ./grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/json
    env_file:
      - .env
    networks:
      - hs-network

volumes:
  thor2_prometheus_data:
  thor2_grafana_data:

networks:
  hs-network:
    driver: bridge
