name: hammerspace-monitoring

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - thor2_prometheus_data:/prometheus
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - hs-network
    

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - thor2_grafana_data:/var/lib/grafana
      - ./grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

    ### Add New Dashboards here
      - ./grafana/dashboards/HammerspaceFileMobility-5.1.json:/etc/grafana/provisioning/dashboards/json/HammerspaceFileMobility-5.1.json                         # File Mobility
      - ./grafana/dashboards/HammerspaceFilesystemReplication-5.1.json:/etc/grafana/provisioning/dashboards/json/HammerspaceFilesystemReplication-5.1.json       # File Replication
      - ./grafana/dashboards/HammerspaceFilesystemStats-5.1.json:/etc/grafana/provisioning/dashboards/json/HammerspaceFilesystemStats-5.1.json                   # Filesystem Stats
      - ./grafana/dashboards/HammerspaceObjectMobility-5.1.json:/etc/grafana/provisioning/dashboards/json/HammerspaceObjectMobility-5.1.json                     # Hammerspace Object Mobility
      - ./grafana/dashboards/HammerspaceProtocolStats-5.1.json:/etc/grafana/provisioning/dashboards/json/HammerspaceProtocolStats-5.1.json                       # Protocol Stats
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin!
    networks:
      - hs-network

volumes:
  thor2_prometheus_data:
  thor2_grafana_data:

networks:
  hs-network:
    driver: bridge
