global:
  evaluation_interval: 15s
  external_labels:
    monitor: example
  scrape_interval: 15s

ips:
  anvil_ip: &anvil_ip 10.200.120.200
  dsx_ip: &dsx_ip 10.200.120.201

scrape_configs:
- job_name: prometheus
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      node_type: prometheus
    targets:
    - localhost:9090

- job_name: cluster
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      cluster: boston
      instance: boston
      node_type: clusterip
    targets:
    - *anvil_ip:9101
    - *anvil_ip:9102
    - *anvil_ip:9103

- job_name: anvil_nodes
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      cluster: boston
      instance: kbk-hs-boston-anvil.onaside.quest.local
      node_type: anvil
    targets:
    - *anvil_ip:9100

- job_name: dsx_nodes
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      cluster: boston
      instance: kbk-hs-boston-dsx1.onaside.quest.local
      node_type: dsx
    targets:
    - *dsx_ip:9100
    - *dsx_ip:9105
