
global:
  evaluation_interval: 15s
  external_labels:
    monitor: example
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      node_type: prometheus
  - targets:
    - localhost:9090

###Modify the following to suit your cluster. This example has a single anvil and a single DSX.    
- job_name: cluster
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      cluster: KBK-HOME
      instance: KBK-HOME
      node_type: clusterip
    targets:
    - 10.200.120.200:9101
    - 10.200.120.200:9102
    - 10.200.120.200:9103
- job_name: anvil_nodes
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      cluster: KBK-HOME
      instance: anvil-site-a.onaside.quest
      node_type: anvil
    targets:
    - 10.200.120.200:9100
- job_name: dsx_nodes
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      cluster: KBK-HOME
      instance: dsx-site-a.onaside.quest
      node_type: dsx
    targets:
<<<<<<< HEAD
    - 10.200.120.201:9100
    - 10.200.120.201:9105

=======
    - 192.168.100.6:9100
    - 192.168.100.6:9105
>>>>>>> refs/remotes/origin/master
