global:
  evaluation_interval: 15s
  external_labels:
    monitor: example
  scrape_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
  - labels:
      node_type: prometheus
    targets:
    - localhost:9090


## Note: Replace the IP addresses with your actual IP addresses
## You can search and replace a.a.a.a with your Cluster IP
## You can search and replace n.n.n.n with your Anvil IP
## You can search and replace x.x.x.x with your DSX IP


## Per Hammerspace documentation, here are the ports used, as well as their function:
            
            ##Anvils:

            ## ENABLED  ✓  UP    ✓  [:9100] node_exporter
            ## ENABLED  ✓  UP    ✓  [:9101] prometheus-dme-exporter
            ## ENABLED  ✓  UP    ✓  [:9103] prometheus-pdfs-exporter
            ## ENABLED  ✓  UP    ✓  [:9102] prometheus-protod-exporter

            ## DSXs:
            
            ## ENABLED  ✓  UP    ✓  [:9100] node_exporter
            ## ENABLED  ✓  UP    ✓  [:9105] prometheus-cm-exporter

- job_name: cluster
  static_configs:
  - labels:
      cluster: your-cluster-name
      instance: your-cluster-name
      node_type: clusterip
    targets:
    - a.a.a.a:9101
    - a.a.a.a:9102
    - a.a.a.a:9103

- job_name: anvil_nodes
  static_configs:
  - labels:
      cluster: your-cluster-name
      instance: your-anvil-name
      node_type: anvil
    targets:
    - n.n.n.n:9100

- job_name: dsx_nodes
  static_configs:
  - labels:
      cluster: your-cluster-name
      instance: your-dsx-name
      node_type: dsx
    targets:
    - x.x.x.x:9100
    - x.x.x.x:9105
