global:
  evaluation_interval: 15s
  external_labels:
    monitor: example
  scrape_interval: 15s

scrape_configs:
- job_name: prometheus
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      node_type: prometheus
    targets:
    - localhost:9090


## Note: Replace the IP addresses with your actual IP addresses
## You can search and replace a.a.a.a with your Cluster IP
## You can search and replace n.n.n.n with your Anvil IP
## You can search and replace x.x.x.x with your DSX IP

- job_name: cluster
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      cluster: boston
      instance: boston
      node_type: clusterip
    targets:
    - a.a.a.a:9101
    - a.a.a.a:9102
    - a.a.a.a:9103

- job_name: anvil_nodes
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      cluster: boston
      instance: kbk-hs-boston-anvil.onaside.quest.local
      node_type: anvil
    targets:
    - n.n.n.n:9100

- job_name: dsx_nodes
  fallback_scrape_protocol: PrometheusText1.0.0
  static_configs:
  - labels:
      cluster: boston
      instance: kbk-hs-boston-dsx1.onaside.quest.local
      node_type: dsx
    targets:
    - x.x.x.x:9100
    - x.x.x.x:9105
