{
 "title": "Hammerspace Object Mobility",
 "tags": [ "Hammerspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hammerspace_exporter_duration,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster:",
    "query": {
     "query": "label_values(hammerspace_exporter_duration{job=~\"$job\"},cluster)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(hammerspace_exporter_duration{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "object_volume",
    "label": "object_volume_id",
    "query": {
     "query": "label_values(hammerspace_object_bucket{instance=~\"$node\"}, bkt_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "File movement <-> Object",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_object_file_download_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[$__rate_interval]))",
     "legendFormat": "downloaded"
    },
    {
     "expr": "sum(rate(hammerspace_object_file_upload_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[$__rate_interval]))",
     "legendFormat": "uploaded"
    },
    {
     "expr": "sum(hammerspace_object_file_upload_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
     "legendFormat": "uploading"
    },
    {
     "expr": "sum(hammerspace_object_file_download_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
     "legendFormat": "downloading"
    }
   ]
  },
  {
   "title": "Chunk movement <-> Object",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_object_chunk_download_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[$__rate_interval]))",
     "legendFormat": "downloaded"
    },
    {
     "expr": "sum(rate(hammerspace_object_chunk_upload_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[$__rate_interval]))",
     "legendFormat": "uploaded"
    },
    {
     "expr": "sum(hammerspace_object_chunk_upload_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
     "legendFormat": "uploading"
    },
    {
     "expr": "sum(hammerspace_object_chunk_download_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
     "legendFormat": "downloading"
    }
   ]
  },
  {
   "title": "Trouble Indicators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(hammerspace_object_file_upload_stage_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stage=\"failed\"}[1m]))",
     "legendFormat": "File upload failures"
    },
    {
     "expr": "sum(idelta(hammerspace_object_file_upload_stage_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stage=\"aborted\"}[1m]))",
     "legendFormat": "File upload aborts"
    },
    {
     "expr": "sum(idelta(hammerspace_object_file_download_stage_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stage=\"failed\"}[1m]))",
     "legendFormat": "File download failures"
    },
    {
     "expr": "sum(idelta(hammerspace_object_file_download_stage_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stage=\"aborted\"}[1m]))",
     "legendFormat": "File donwload aborts"
    },
    {
     "expr": "sum(idelta(hammerspace_object_chunk_upload_stage_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stage=\"failed\"}[1m]))",
     "legendFormat": "Chunk upload failures"
    },
    {
     "expr": "sum(idelta(hammerspace_object_chunk_download_stage_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stage=\"failed\"}[1m]))",
     "legendFormat": "Chunk upload aborts"
    },
    {
     "expr": "idelta(hammerspace_object_unreachable{job=~\"$job\"}[1m])",
     "legendFormat": "CM Unreachable {{instance}}"
    },
    {
     "expr": "sum by (op) (idelta(hammerspace_object_nfs_op_fail{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"}[1m]))",
     "legendFormat": "NFS OP {{op}} failed on {{volid}}"
    }
   ]
  },
  {
   "title": "Chunks per file",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(hammerspace_object_chunk_download_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[1m])) / sum(delta(hammerspace_object_file_download_count{cluster=~\"$cluster\",cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[1m]))",
     "legendFormat": "chunks per file download"
    },
    {
     "expr": "sum(delta(hammerspace_object_chunk_upload_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[1m])) / sum(delta(hammerspace_object_file_upload_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[1m]))",
     "legendFormat": "chunks per file upload"
    }
   ]
  },
  {
   "title": "50th Percentile File Processing Time: Sum of p50 stages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hammerspace_object_file_upload_stage_ms{cluster=~\"$cluster\",cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"mean\",queue=\"0\"})",
     "legendFormat": "upload p50 sum ACTIVE"
    },
    {
     "expr": "sum(hammerspace_object_file_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"mean\",queue=\"0\"})",
     "legendFormat": "download p50 sum ACTIVE"
    },
    {
     "expr": "sum(hammerspace_object_file_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"mean\",queue=\"1\"})",
     "legendFormat": "upload p50 sum IDLE"
    },
    {
     "expr": "sum(hammerspace_object_file_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"mean\",queue=\"1\"})",
     "legendFormat": "download p50 sum IDLE"
    }
   ]
  },
  {
   "title": "50th Percentile Chunk Processing Time: Sum of p50 stages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hammerspace_object_chunk_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"mean\",queue=\"0\"})",
     "legendFormat": "upload p50 sum ACTIVE"
    },
    {
     "expr": "sum(hammerspace_object_chunk_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"mean\",queue=\"0\"})",
     "legendFormat": "download p50 sum ACTIVE"
    },
    {
     "expr": "sum(hammerspace_object_chunk_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"mean\",queue=\"1\"})",
     "legendFormat": "upload p50 sum IDLE"
    },
    {
     "expr": "sum(hammerspace_object_chunk_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"mean\",queue=\"1\"})",
     "legendFormat": "download p50 sum IDLE"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Physical Bandwidth (compressed and deduped, MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_object_bytes_downloaded_physical{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[$__rate_interval]))/1024/1024",
     "legendFormat": "downloaded"
    },
    {
     "expr": "sum(rate(hammerspace_object_bytes_uploaded_physical{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[$__rate_interval]))/1024/1024",
     "legendFormat": "uploaded"
    }
   ]
  },
  {
   "title": "Logical Bandwidth (MB/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_object_bytes_downloaded_logical{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[$__rate_interval]))/1024/1024",
     "legendFormat": "downloaded"
    },
    {
     "expr": "sum(rate(hammerspace_object_bytes_uploaded_logical{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[$__rate_interval]))/1024/1024",
     "legendFormat": "uploaded"
    }
   ]
  },
  {
   "title": "Physical Bandwidth 15min avg (compressed and deduped, MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_object_bytes_downloaded_physical{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[15m]))/1024/1024",
     "legendFormat": "downloaded 15min"
    },
    {
     "expr": "sum(rate(hammerspace_object_bytes_uploaded_physical{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[15m]))/1024/1024",
     "legendFormat": "uploaded 15min"
    }
   ]
  },
  {
   "title": "Logical Bandwidth 15min avg (MB/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_object_bytes_downloaded_logical{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[15m]))/1024/1024",
     "legendFormat": "downloaded 15m"
    },
    {
     "expr": "sum(rate(hammerspace_object_bytes_uploaded_logical{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}[15m]))/1024/1024",
     "legendFormat": "uploaded 15m"
    }
   ]
  },
  {
   "title": "Chunks and Files by DSX node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunks completed by node",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(hammerspace_object_chunk_download_count{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$node\",bkt_id=~\"$object_volume\"}[$__rate_interval])) + sum by (instance) (rate(hammerspace_object_chunk_upload_count{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$node\",bkt_id=~\"$object_volume\"}[$__rate_interval]))",
       "legendFormat": "Completed {{instance}}"
      }
     ]
    },
    {
     "title": "Chunks in process by node",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (hammerspace_object_chunk_download_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}) + sum by (instance) (hammerspace_object_chunk_upload_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
       "legendFormat": "Active {{instance}}"
      }
     ]
    },
    {
     "title": "Files completed by node",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(hammerspace_object_file_download_count{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$node\",bkt_id=~\"$object_volume\"}[$__rate_interval])) + sum by (instance) (rate(hammerspace_object_file_upload_count{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$node\",bkt_id=~\"$object_volume\"}[$__rate_interval]))",
       "legendFormat": "Completed {{instance}}"
      }
     ]
    },
    {
     "title": "Files in process by node",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (hammerspace_object_file_download_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"}) + sum by (instance) (hammerspace_object_file_upload_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
       "legendFormat": "Active {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Time in queue percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "File: p99 milliseconds ACTIVE in queue by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "hammerspace_object_file_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p99\",queue=\"0\"}",
       "legendFormat": "up {{stage}}"
      },
      {
       "expr": "hammerspace_object_file_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p99\",queue=\"0\"}",
       "legendFormat": "down {{stage}}"
      }
     ]
    },
    {
     "title": "File: p50 milliseconds ACTIVE in queue by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "hammerspace_object_file_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p50\",queue=\"0\"}",
       "legendFormat": "up {{stage}}"
      },
      {
       "expr": "hammerspace_object_file_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p50\",queue=\"0\"}",
       "legendFormat": "down {{stage}}"
      }
     ]
    },
    {
     "title": "File: p99 milliseconds IDLE by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "hammerspace_object_file_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p99\",queue=\"1\"}",
       "legendFormat": "up {{stage}}"
      },
      {
       "expr": "hammerspace_object_file_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p99\",queue=\"1\"}",
       "legendFormat": "down {{stage}}"
      }
     ]
    },
    {
     "title": "File: p50 milliseconds IDLE in queue by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "hammerspace_object_file_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p50\",queue=\"1\"}",
       "legendFormat": "up {{stage}}"
      },
      {
       "expr": "hammerspace_object_file_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p50\",queue=\"1\"}",
       "legendFormat": "down {{stage}}"
      }
     ]
    },
    {
     "title": "Chunk: p99 milliseconds ACTIVE in queue by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "hammerspace_object_chunk_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p99\",queue=\"0\"}",
       "legendFormat": "up {{stage_num}} {{stage}}"
      },
      {
       "expr": "hammerspace_object_chunk_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p99\",queue=\"0\"}",
       "legendFormat": "down {{stage_num}} {{stage}}"
      }
     ]
    },
    {
     "title": "Chunk: p50 milliseconds ACTIVE in queue by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "hammerspace_object_chunk_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p50\",queue=\"0\"}",
       "legendFormat": "up {{stage_num}} {{stage}}"
      },
      {
       "expr": "hammerspace_object_chunk_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p50\",queue=\"0\"}",
       "legendFormat": "down {{stage_num}} {{stage}}"
      }
     ]
    },
    {
     "title": "Chunk: p99 milliseconds IDLE in queue by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "hammerspace_object_chunk_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p99\",queue=\"1\"}",
       "legendFormat": "up {{stage_num}} {{stage}}"
      },
      {
       "expr": "hammerspace_object_chunk_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p99\",queue=\"1\"}",
       "legendFormat": "down {{stage_num}} {{stage}}"
      }
     ]
    },
    {
     "title": "Chunk: p50 milliseconds IDLE in queue by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "hammerspace_object_chunk_upload_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p50\",queue=\"1\"}",
       "legendFormat": "up {{stage_num}} {{stage}}"
      },
      {
       "expr": "hammerspace_object_chunk_download_stage_ms{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\",stat=\"p50\",queue=\"1\"}",
       "legendFormat": "down {{stage_num}} {{stage}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Items in Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "File: items in processing queue by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum by (stage) (hammerspace_object_file_upload_stage_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
       "legendFormat": "up {{stage}}"
      },
      {
       "expr": "sum by (stage) (hammerspace_object_file_download_stage_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
       "legendFormat": "down {{stage}}"
      }
     ]
    },
    {
     "title": "Chunk: items in queue by stage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sum by (stage) (hammerspace_object_chunk_upload_stage_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
       "legendFormat": "up {{stage}}"
      },
      {
       "expr": "sum by (stage) (hammerspace_object_chunk_download_stage_processing{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",bkt_id=~\"$object_volume\"})",
       "legendFormat": "down {{stage}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool Active Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum by (threadpool, priority) (hammerspace_object_threadpool_used{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"})",
       "legendFormat": "{{threadpool}} {{priority}}"
      }
     ]
    },
    {
     "title": "Items blocked waiting for slot in threadpool",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum by (threadpool, priority) (hammerspace_object_threadpool_waitingfor{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"})",
       "legendFormat": "{{threadpool}} {{priority}}"
      }
     ]
    },
    {
     "title": "Breakdown threadpool detailed analysis",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "sum by (uldl, priority) (hammerspace_object_threadpool_waitingfor{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",threadpool=\"breakdown\"})",
       "legendFormat": "queued breakdown {{uldl}} {{priority}}"
      },
      {
       "expr": "sum by (uldl, priority) (hammerspace_object_threadpool_used{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\",threadpool=\"breakdown\"})",
       "legendFormat": "running breakdown {{uldl}} {{priority}}"
      }
     ]
    }
   ]
  },
  { "title": "IO Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "IO Buffers total bytes in use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(hammerspace_object_iobuffer_bytes_used{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "Bytes Used MB"
    }
   ]
  },
  {
   "title": "IO Buffer Allocation Rate/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_object_iobuffer_allocations{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Allocations"
    }
   ]
  },
  {
   "title": "IO Buffer allocation size stats, in MB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by (stat) (hammerspace_object_iobuffer_stats{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"}/1024/1024)",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  { "title": "NFS ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "NFS Bytes/second all volumes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum by (op) (rate(hammerspace_object_nfs_op_bytes{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"}[30s]))",
     "legendFormat": "{{op}} "
    }
   ]
  },
  {
   "title": "NFS Bytes/second all volumes per CM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by (op, instance) (irate(hammerspace_object_nfs_op_bytes{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"}[30s]))",
     "legendFormat": "{{op}} {{instance}}"
    }
   ]
  },
  {
   "title": "NFS Bytes/second per volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "rate(hammerspace_object_nfs_op_bytes{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"}[30s])",
     "legendFormat": "{{op}} {{volid}}"
    }
   ]
  },
  {
   "title": "NFS OP/s completed to all volumes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum by (op) (rate(hammerspace_object_nfs_op_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"}[30s]))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "NFS OP/s completed by volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "rate(hammerspace_object_nfs_op_count{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"}[30s])",
     "legendFormat": "{{op}} {{volid}}"
    }
   ]
  },
  {
   "title": "NFS OP/s in flight by volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "rate(hammerspace_object_nfs_op_inflight{cluster=~\"$cluster\",instance=~\"$node\",job=~\"$job\"}[30s])",
     "legendFormat": "{{op}} {{volid}}"
    }
   ]
  }
 ]
}