{
 "title": "Hammerspace Filesystem Stats",
 "tags": [ "Hammerspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hammerspace_exporter_duration,job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(hammerspace_exporter_duration{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "share",
    "label": "Share",
    "query": {
     "query": "label_values(hammerspace_filesystem_ops,share)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Open Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of open files all shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hammerspace_filesystem_open_files{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "Open Files"
    },
    {
     "expr": "sum(avg_over_time(hammerspace_filesystem_open_files{instance=~\"$node\",job=~\"$job\"}[15m]))",
     "legendFormat": "15 min avg"
    }
   ]
  },
  {
   "title": "Number of open files by share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hammerspace_filesystem_open_files{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}",
     "legendFormat": "Open Files {{share}}"
    }
   ]
  },
  { "title": "Filesystem Sweeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total items swept / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_sweeper_current_run_swept_count{instance=~\"$node\",job=~\"$job\",share=~\"$share\",sweep_type!=\"files\"}[$__rate_interval]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_sweeper_current_run_swept_count{instance=~\"$node\",job=~\"$job\",share=~\"$share\",sweep_type!=\"files\"}[15m]))",
     "legendFormat": "15 min avg"
    }
   ]
  },
  {
   "title": "Total items swept / sec by Share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_sweeper_current_run_swept_count{instance=~\"$node\",job=~\"$job\",sweep_type!=\"files\"}[$__rate_interval])) by (share)",
     "legendFormat": "{{share}}"
    }
   ]
  },
  {
   "title": "New sweep runs started by Share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(delta(hammerspace_filesystem_sweeper_current_run_number{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) by (share) != 0",
     "legendFormat": "{{share}}"
    }
   ]
  },
  {
   "title": "Current sweep duration in hours by Share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "max(hammerspace_filesystem_sweeper_current_run_time{instance=~\"$node\",job=~\"$job\"}/60/60) by (share)",
     "legendFormat": "{{share}}"
    }
   ]
  },
  { "title": "Filesystem Sweeper Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Files vs Non-Files sweep rate/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_sweeper_current_run_swept_count{instance=~\"$node\",job=~\"$job\",share=~\"$share\",sweep_type=\"files\"}[$__rate_interval]))",
     "legendFormat": "files/s"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_sweeper_current_run_swept_count{instance=~\"$node\",job=~\"$job\",share=~\"$share\",sweep_type=\"non-files\"}[$__rate_interval]))",
     "legendFormat": "non-files/s"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_sweeper_current_run_swept_count{instance=~\"$node\",job=~\"$job\",share=~\"$share\",sweep_type=\"items\"}[$__rate_interval]))",
     "legendFormat": "files_items/s"
    }
   ]
  },
  {
   "title": "sweeper errors / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_sweeper_current_run_swept_errors_count{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval])) by (ret_name)",
     "legendFormat": "{{ret_name}}"
    }
   ]
  },
  { "title": "OP Return Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Filesystem Op Non-Zero Return Code Counts / second (shares = $share)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op, ret_name, ret_num)",
     "legendFormat": "{{op}} {{ret_name}} ({{ret_num}}) (B)"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op, ret_name, ret_num)",
     "legendFormat": "{{op}} {{ret_name}} ({{ret_num}})"
    }
   ]
  },
  {
   "title": "% of non-zero filesystem op return codes (shares = $share)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op) / sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval])) by (op))*100",
     "legendFormat": "{{op}} {{ret_name}} ({{ret_num}})"
    },
    {
     "expr": "(sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op) / sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) by (op))*100",
     "legendFormat": "{{op}} {{ret_name}} ({{ret_num}}) (B)"
    }
   ]
  },
  {
   "title": "op counts, 0 vs non-zero",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op) ",
     "legendFormat": "{{op}} nonzero"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\",ret_num=~\"0\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}}"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\",ret_num=~\"0\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}} (B)"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}} nonzero (B)"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Ticks spent interfacing with KVS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum by (ttype) (rate(hammerspace_filesystem_kvs_cycles{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "{{ttype}}"
      }
     ]
    },
    {
     "title": "Internal Caches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "sum by (type) (hammerspace_filesystem_internal_cache_entries{instance=~\"$node\",job=~\"$job\",share=~\"$share\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Commits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "sum by (ctype) (rate(hammerspace_filesystem_kvs_commit{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "{{ctype}}"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "hammerspace_filesystem_memory{instance=~\"$node\",job=~\"$job\",share=\"/\"}/1024/1024",
       "legendFormat": "MB {{memtype}}"
      }
     ]
    },
    {
     "title": "KV Bytes Written",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_filesystem_kvs_write_bytes{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "KV Bytes Written"
      }
     ]
    }
   ]
  },
  {
   "title": "Inter component communication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Internal Communication Events (shares = $share)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_filesystem_dme_compliance_updates{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "Received (DME)"
      },
      {
       "expr": "sum(rate(hammerspace_filesystem_dme_events_sent{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "Sent (DME)"
      }
     ]
    },
    {
     "title": "Internal Communication Event CPU Cycles (shares = $share)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_filesystem_dme_compliance_updates_cycles{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "Received (DME)"
      },
      {
       "expr": "sum(rate(hammerspace_filesystem_dme_events_sent_cycles{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "Sent (DME)"
      }
     ]
    }
   ]
  },
  {
   "title": "OP Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "filesystem ops per second (shares=$share)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) by (op)",
       "legendFormat": "{{op}} (B)"
      },
      {
       "expr": "sum(rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval])) by (op)",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "aggragate filesystem ops per second (shares=$share)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum(rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]))",
       "legendFormat": "Background Ops"
      },
      {
       "expr": "sum(rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval]))",
       "legendFormat": "Other Ops"
      }
     ]
    },
    {
     "title": "milisec cpu busy per op by type (shares = $share)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum((rate(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) / rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) / 1000) by (op)",
       "legendFormat": "{{op}} (B)"
      }
     ]
    },
    {
     "title": "milisec cpu stalled per op by type (shares = $share)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "sum((rate(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) / rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) / 1000) by (op)",
       "legendFormat": "{{op}} (B)"
      }
     ]
    }
   ]
  },
  {
   "title": "OP Raw",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "filesystem ops per sample (rate is above) (shares=$share)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum(delta(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) by (op)",
       "legendFormat": "{{op}} (B)"
      },
      {
       "expr": "sum(delta(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval])) by (op)",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "milisec cpu busy by op type (shares = $share)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(delta(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval]) / 1000) by (op)",
       "legendFormat": "{{op}}"
      },
      {
       "expr": "sum(delta(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) / 1000) by (op)",
       "legendFormat": "{{op}} (B)"
      }
     ]
    },
    {
     "title": "milisec cpu stalled by op type (shares = $share)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum(delta(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval]) / 1000) by (op)",
       "legendFormat": "{{op}}"
      },
      {
       "expr": "sum(delta(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) / 1000) by (op)",
       "legendFormat": "{{op}} (B)"
      }
     ]
    },
    {
     "title": "milisec total cpu (used+stalled) by op type (shares = $share)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "sum((delta(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval]) + delta(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval])) / 1000) by (op)",
       "legendFormat": "{{op}}"
      },
      {
       "expr": "sum((delta(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) + delta(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) / 1000) by (op)",
       "legendFormat": "{{op}} (B)"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS3 ops issued against storage volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }
  },
  {
   "title": "NFSv3 ops/sec issued against storage volumes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (op) (rate(hammerspace_filesystem_nfs3_ops{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "ms waiting for NFSv3 ops issued against storage volumes/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (op) (rate(hammerspace_filesystem_nfs3_ops_usec{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]))/1000",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Average time per NFS3 op in ms/sample",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(hammerspace_filesystem_nfs3_ops_usec{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]) /  delta(hammerspace_filesystem_nfs3_ops{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{op}} {{share}}"
    }
   ]
  },
  {
   "title": "Latency by op by volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (op, volumeid) (rate(hammerspace_filesystem_nfs3_ops_usec{instance=~\"$node\",job=~\"$job\"}[$__rate_interval]))/1000 != 0",
     "legendFormat": "{{volumeid}} {{op}} "
    }
   ]
  },
  {
   "title": "Error codes returned by nfs3 op by volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (op, ret_name, ret_num, volumeid) (delta(hammerspace_filesystem_nfs3_op_results{instance=~\"$node\",job=~\"$job\",ret_num!=\"0\"}[$__rate_interval])) != 0",
     "legendFormat": "vol {{volumeid}} {{op}} ({{ret_num}}) {{ret_name}}"
    }
   ]
  }
 ]
}