{
 "title": "Hammerspace Filesystem Stats",
 "tags": [ "Hammerspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hammerspace_filesystem_exporter_build_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(hammerspace_filesystem_exporter_build_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "share",
    "label": "Share",
    "query": {
     "query": "label_values(hammerspace_filesystem_ops,share)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Open Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of open files all shares",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hammerspace_filesystem_open_files{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "Open Files"
    },
    {
     "expr": "sum(avg_over_time(hammerspace_filesystem_open_files{instance=~\"$node\",job=~\"$job\"}[15m]))",
     "legendFormat": "15 min avg"
    }
   ]
  },
  {
   "title": "Number of open files by share",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hammerspace_filesystem_open_files{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}",
     "legendFormat": "Open Files {{share}}"
    }
   ]
  },
  { "title": "OP Return Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Filesystem Op Non-Zero Return Code Counts / sample (shares = $share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops / sample" }
   ],
   "targets": [
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op, ret_name, ret_num)",
     "legendFormat": "{{op}} {{ret_name}} ({{ret_num}}) (B)"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op, ret_name, ret_num)",
     "legendFormat": "{{op}} {{ret_name}} ({{ret_num}})"
    }
   ]
  },
  {
   "title": "% of non-zero filesystem op return codes (shares = $share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op) / sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval])) by (op))*100",
     "legendFormat": "{{op}} {{ret_name}} ({{ret_num}})"
    },
    {
     "expr": "(sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op) / sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) by (op))*100",
     "legendFormat": "{{op}} {{ret_name}} ({{ret_num}}) (B)"
    }
   ]
  },
  {
   "title": "op counts, 0 vs non-zero",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op) ",
     "legendFormat": "{{op}} nonzero"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\",ret_num=~\"0\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}}"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\",ret_num=~\"0\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}} (B)"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\",ret_num!=\"0\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}} nonzero (B)"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Ticks spent interfacing with KVS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ttype) (rate(hammerspace_filesystem_kvs_cycles{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "{{ttype}}"
      }
     ]
    },
    {
     "title": "Internal Caches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (hammerspace_filesystem_internal_cache_entries{instance=~\"$node\",job=~\"$job\",share=~\"$share\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Commits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ctype) (rate(hammerspace_filesystem_kvs_commit{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "{{ctype}}"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hammerspace_filesystem_memory{instance=~\"$node\",job=~\"$job\",share=\"/\"}/1024/1024",
       "legendFormat": "MB {{memtype}}"
      }
     ]
    },
    {
     "title": "KV Bytes Written",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hammerspace_filesystem_kvs_write_bytes{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "KV Bytes Written"
      }
     ]
    }
   ]
  },
  {
   "title": "Inter component communication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Internal Communication Events (shares = $share)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hammerspace_filesystem_dme_compliance_updates{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "Received (DME)"
      },
      {
       "expr": "sum(rate(hammerspace_filesystem_dme_events_sent{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "Sent (DME)"
      }
     ]
    },
    {
     "title": "Internal Communication Event CPU Cycles (shares = $share)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hammerspace_filesystem_dme_compliance_updates_cycles{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "Received (DME)"
      },
      {
       "expr": "sum(rate(hammerspace_filesystem_dme_events_sent_cycles{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
       "legendFormat": "Sent (DME)"
      }
     ]
    }
   ]
  },
  { "title": "OP Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "filesystem ops per second (shares=$share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}} (B)"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "aggragate filesystem ops per second (shares=$share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]))",
     "legendFormat": "Background Ops"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval]))",
     "legendFormat": "Other Ops"
    }
   ]
  },
  {
   "title": "milisec cpu busy per op by type (shares = $share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "sum((rate(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) / rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) / 1000) by (op)",
     "legendFormat": "{{op}} (B)"
    }
   ]
  },
  {
   "title": "milisec cpu stalled per op by type (shares = $share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "sum((rate(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) / rate(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) / 1000) by (op)",
     "legendFormat": "{{op}} (B)"
    }
   ]
  },
  { "title": "OP Raw", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "filesystem ops (shares=$share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}} (B)"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval])) by (op)",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "milisec cpu busy by op type (shares = $share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval]) / 1000) by (op)",
     "legendFormat": "{{op}}"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) / 1000) by (op)",
     "legendFormat": "{{op}} (B)"
    }
   ]
  },
  {
   "title": "milisec cpu stalled by op type (shares = $share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval]) / 1000) by (op)",
     "legendFormat": "{{op}}"
    },
    {
     "expr": "sum(delta(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) / 1000) by (op)",
     "legendFormat": "{{op}} (B)"
    }
   ]
  },
  {
   "title": "milisec total cpu (used+stalled) by op type (shares = $share)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short", "label": "Client Path Ops" }
   ],
   "targets": [
    {
     "expr": "sum((delta(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval]) + delta(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background!=\"1\"}[$__rate_interval])) / 1000) by (op)",
     "legendFormat": "{{op}}"
    },
    {
     "expr": "sum((delta(hammerspace_filesystem_ops_wait_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval]) + delta(hammerspace_filesystem_ops_busy_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\",background=~\"1\"}[$__rate_interval])) / 1000) by (op)",
     "legendFormat": "{{op}} (B)"
    }
   ]
  },
  {
   "title": "NFS3 ops issued against storage volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 }
  },
  {
   "title": "NFSv3 ops issued against storage volumes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (op) (rate(hammerspace_filesystem_nfs3_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "ms waiting for NFSv3 ops issued against storage volumes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (op) (rate(hammerspace_filesystem_nfs3_ops_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]))/1000",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Average time per NFS3 op in ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(hammerspace_filesystem_nfs3_ops_usec{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval]) /  delta(hammerspace_filesystem_nfs3_ops{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}[$__rate_interval])",
     "legendFormat": "{{op}} {{share}}"
    }
   ]
  }
 ]
}