{
 "title": "Hammerspace File Mobility",
 "tags": [ "Hammerspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(dme_exporter_build_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(dme_exporter_build_info{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "File Movement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mobility jobs attempted",
   "type": "timeseries",
   "description": "Mobility jobs where an attempt is made.  ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(hammerspace_mobility_jobs_run{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job_type}}"
    }
   ]
  },
  {
   "title": "Files queued for mobility",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(hammerspace_actuary_queued_for_mobility_files{instance=~\"$node\",job=~\"$job\"}[1m])",
     "legendFormat": "files queued"
    },
    {
     "expr": "rate(hammerspace_actuary_queued_for_mobility_files{instance=~\"$node\",job=~\"$job\"}[15m]) * 60",
     "legendFormat": "15 min avg"
    }
   ]
  },
  {
   "title": "Mobility jobs at time of sample",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hammerspace_mobility_actively_moving_files{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Live {{status}}"
    }
   ]
  },
  {
   "title": "Active/Queued mobility jobs by Duration (minutes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "hammerspace_mobility_actively_moving_files_seconds{instance=~\"$node\",job=~\"$job\"}/60",
     "legendFormat": "{{stat}} minutes"
    }
   ]
  },
  {
   "title": "Active (not queued) mobility jobs by size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "hammerspace_mobility_actively_moving_files_bytes{instance=~\"$node\",job=~\"$job\"}/1024/1024",
     "legendFormat": "{{stat}} MB"
    }
   ]
  },
  {
   "title": "File Movement Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Actuary runs and convergence",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Events per Minute" }
   ],
   "targets": [
    {
     "expr": "delta(hammerspace_actuary_non_convergence_events{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Non-Convergence Events"
    },
    {
     "expr": "delta(hammerspace_actuary_cycles{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Run Cycles"
    }
   ]
  },
  {
   "title": "Actuary Iterations per cycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hammerspace_actuary_iterations_per_cycle{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "Actuary compute ms per cycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hammerspace_actuary_nanoseconds_per_cycle{instance=~\"$node\",job=~\"$job\"} / 1000000",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "Alignment Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "File alignment checks / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hammerspace_grading_files_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Files checked for allignment"
    },
    {
     "expr": "rate(hammerspace_grading_misaligned_files_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Misalligned files found"
    },
    {
     "expr": "rate(hammerspace_grading_files_count{instance=~\"$node\",job=~\"$job\"}[15m])",
     "legendFormat": "Files checked for alignment 15 min avg"
    },
    {
     "expr": "rate(hammerspace_grading_misaligned_files_count{instance=~\"$node\",job=~\"$job\"}[15m])",
     "legendFormat": "Misalligned files found 15min avg"
    }
   ]
  },
  {
   "title": "File alignment checks by producer / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hammerspace_grading_files_producer_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Alignment Analysis Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Grader books insertions / evictions rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hammerspace_grading_books_insertion_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Insertions"
    },
    {
     "expr": "-1*rate(hammerspace_grading_books_eviction_count{instance=~\"$node\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Evictions"
    },
    {
     "expr": "rate(hammerspace_grading_books_insertion_count{instance=~\"$node\",job=~\"$job\"}[15m])",
     "legendFormat": "Insertions 15m avg"
    },
    {
     "expr": "-1*rate(hammerspace_grading_books_eviction_count{instance=~\"$node\",job=~\"$job\"}[15m])",
     "legendFormat": "Evictions 15m avg"
    }
   ]
  },
  {
   "title": "Grading time per file/object (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hammerspace_grading_time_nanoseconds_per_cycle{instance=~\"$node\",job=~\"$job\"} / 1000000",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "Placement tests per file graded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hammerspace_grading_alternatives_per_file{instance=~\"$node\",job=~\"$job\"}  ",
     "legendFormat": "{{stat}}/file"
    }
   ]
  },
  {
   "title": "RPC counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPC Connects / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hammerspace_dme_rpc_connect_count{instance=~\"$node\",job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC Disconnects / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hammerspace_dme_rpc_disconnect_count{instance=~\"$node\",job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC Backend Data Blobs Deletes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hammerspace_dme_rpc_delete_object_count{instance=~\"$node\",job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC Backend data blob updates / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hammerspace_dme_rpc_update_object_count{instance=~\"$node\",job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC backend data blob meta modifications / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hammerspace_dme_rpc_request_instance_count{instance=~\"$node\",job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC COW split counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPC backend data blob COW split allocations / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hammerspace_dme_rpc_request_instance_cow_split_count{instance=~\"$node\",job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC COW split setups / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hammerspace_dme_rpc_setup_cow_split_count{instance=~\"$node\",job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC COW split starts / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hammerspace_dme_rpc_start_cow_split_count{instance=~\"$node\",job=~\"$job\"}[1m])"
    }
   ]
  }
 ]
}