{
 "title": "Hammerspace Filesystem Replication",
 "tags": [ "Hammerspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hammerspace_filesystem_exporter_build_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(hammerspace_filesystem_exporter_build_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "share",
    "label": "Share",
    "query": {
     "query": "label_values(hammerspace_filesystem_ops,share)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "README", "type": "text", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } }
   ]
  },
  { "title": "Seconds Behind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Worst Share Send Seconds Behind by Sender",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(hammerspace_filesystem_replication_send_behind{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}) by (from_site)",
     "legendFormat": "{{from_site}}"
    }
   ]
  },
  {
   "title": "Worst Share Send Seconds Behind by Reciever",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(hammerspace_filesystem_replication_send_behind{instance=~\"$node\",job=~\"$job\",share=~\"$share\"}) by (to_site)",
     "legendFormat": "{{to_site}}"
    }
   ]
  },
  {
   "title": "Send Seconds Behind Delta",
   "type": "timeseries",
   "description": "Bouncing around zero is good, consistent positive is bad.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(from_site) (deriv(hammerspace_filesystem_replication_send_behind{instance=~\"$node\", job=~\"$job\", share=~\"$share\"}[1m]))",
     "legendFormat": "{{from_site}}"
    }
   ]
  },
  {
   "title": "Send rate and success vs failure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of replication send activity -- all sites",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",share=~\"$share\",status=\"sent\"}[$__rate_interval]))",
     "legendFormat": "Sends"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",share=~\"$share\",status=\"sent\"}[15m]))",
     "legendFormat": "Sends 15 min avg"
    }
   ]
  },
  {
   "title": "Successful SNAP sends/second -- by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",status=\"ok\",share=~\"$share\",type=\"snap\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Sends Success {{instance}}"
    }
   ]
  },
  {
   "title": "Failed SNAP sends/second -- by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",status=\"fail\",share=~\"$share\",type=\"snap\"}[$__rate_interval])) by (instance) *-1",
     "legendFormat": "Sends Failed {{instance}}"
    }
   ]
  },
  {
   "title": "Successful INODE sends/second -- by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",status=\"ok\",share=~\"$share\",type=\"inode\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Sends Success {{instance}}"
    }
   ]
  },
  {
   "title": "Failed INODE sends/second -- by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",status=\"fail\",share=~\"$share\",type=\"inode\"}[$__rate_interval])) by (instance) *-1",
     "legendFormat": "Sends Failed {{instance}}"
    }
   ]
  },
  {
   "title": "Rate of replication sends by type and success -- all sites",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",type=\"snap\",status=\"ok\",share=~\"$share\"}[$__rate_interval]))",
     "legendFormat": "SNAP Sends Success"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",type=\"snap\",status=\"fail\",share=~\"$share\"}[$__rate_interval]))*-1",
     "legendFormat": "SNAP Sends Failed"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",type=\"inode\",status=\"ok\",share=~\"$share\"}[$__rate_interval]))",
     "legendFormat": "INODE Sends Success"
    },
    {
     "expr": "sum(rate(hammerspace_filesystem_replication_send{instance=~\"$node\",job=~\"$job\",type=\"inode\",status=\"fail\",share=~\"$share\"}[$__rate_interval]))*-1",
     "legendFormat": "INODE Sends Failed"
    }
   ]
  },
  {
   "title": "Merge attempts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Replication merge attempts by return code -- all sites",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replication_merge_recs\"}[$__rate_interval])) by (ret_name, ret_num)",
     "legendFormat": "merges {{ret_name}} ({{ret_num}})"
    }
   ]
  },
  {
   "title": "% of merge attempts that are non-zero -- per site",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n(sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replication_merge_recs\",ret_num!=\"0\"}[$__rate_interval])) by (instance))\n /\n(sum(delta(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replication_merge_recs\"}[$__rate_interval])) by (instance))\n)*100",
     "legendFormat": "% non-zero {{instance}}"
    }
   ]
  },
  {
   "title": "Rate of merge attempts that succeed -- per site",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hammerspace_filesystem_op_results{instance=~\"$node\",job=~\"$job\",share=~\"$share\",op=\"replication_merge_recs\",ret_num=\"0\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Rate of merge success {{instance}}"
    }
   ]
  }
 ]
}