{
 "title": "Hammerspace Protocol Stats",
 "tags": [ "Hammerspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hammerspace_protod_exporter_build_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(hammerspace_protod_exporter_build_info{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read/Write metadata ops / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_metadata_ops{instance=~\"$node\",job=~\"$job\",type=~\"read\"}[1m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "irate(hammerspace_protod_metadata_ops{instance=~\"$node\",job=~\"$job\",type=~\"write\"}[1m])*-1",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Compound ops / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_compound_ops{instance=~\"$node\",job=~\"$job\",type=~\"success\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "irate(hammerspace_protod_compound_ops{instance=~\"$node\",job=~\"$job\",type=~\"error\"}[1m])*-1",
     "legendFormat": "Retry"
    }
   ]
  },
  {
   "title": "File creation & deletion / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_file_create_ops{instance=~\"$node\",job=~\"$job\"}[1m])",
     "legendFormat": "Create"
    },
    {
     "expr": "irate(hammerspace_protod_file_delete_ops{instance=~\"$node\",job=~\"$job\"}[1m])*-1",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "delegation stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_delegations{instance=~\"$node\",job=~\"$job\",type=\"granted\"}[1m])",
     "legendFormat": "Granted / sec"
    },
    {
     "expr": "irate(hammerspace_protod_delegations{instance=~\"$node\",job=~\"$job\",type=\"denied\"}[1m])*-1",
     "legendFormat": "Denied / sec"
    },
    {
     "expr": "hammerspace_protod_delegations{instance=~\"$node\",job=~\"$job\",type=\"active_delegations\"}",
     "legendFormat": "Active Delegations"
    }
   ]
  },
  {
   "title": "file open stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hammerspace_protod_opens{instance=~\"$node\",job=~\"$job\",type=\"granted\"}[1m])",
     "legendFormat": "Opens  / sec"
    },
    {
     "expr": "irate(hammerspace_protod_opens{instance=~\"$node\",job=~\"$job\",type=\"denied\"}[1m])*-1",
     "legendFormat": "Opens Denied / sec"
    },
    {
     "expr": "hammerspace_protod_opens{instance=~\"$node\",job=~\"$job\",type=\"currently_open\"}",
     "legendFormat": "Open files"
    }
   ]
  },
  {
   "title": "Individual Op Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NFS ops / second at protocol layer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m])",
     "legendFormat": "{{servicer}} {{op}}"
    }
   ]
  },
  {
   "title": "NFS ops / second from protocol passed to filesystem",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m])",
     "legendFormat": "{{servicer}} {{op}}"
    }
   ]
  },
  {
   "title": "NFS ops / second from protocol against storage volumes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hammerspace_nfs_protocol_ops_to_storage_volumes{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m])",
     "legendFormat": "{{servicer}} {{op}}"
    }
   ]
  },
  {
   "title": "NFS ops / second from shadow files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"shadow\"}[1m])",
     "legendFormat": "{{servicer}} {{op}}"
    }
   ]
  },
  {
   "title": "Individual op counts raw",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NFS ops at protocol layer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m])",
     "legendFormat": "{{servicer}} {{op}}"
    }
   ]
  },
  {
   "title": "NFS ops from protocol passed to filesystem",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m])",
     "legendFormat": "{{servicer}} {{op}}"
    }
   ]
  },
  {
   "title": "NFS ops from protocol against storage volumes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(hammerspace_nfs_protocol_ops_to_storage_volumes{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m])",
     "legendFormat": "{{servicer}} {{op}}"
    }
   ]
  },
  {
   "title": "NFS ops from shadow files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"shadow\"}[1m])",
     "legendFormat": "{{servicer}} {{op}}"
    }
   ]
  },
  {
   "title": "Walltime per Individual Op at each layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Milliseconds / op at protocol layer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "Milliseconds / op at filesystem layer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m]) / irate(hammerspace_nfs_protocol_ops{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "Milliseconds / op sent to storage volumes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_to_storage_volumes_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / irate(hammerspace_nfs_protocol_ops_to_storage_volumes{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Walltime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Milliseconds by op type at protocol layer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "Total Milliseconds by op type at filesystem layer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"filesystem\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    },
    {
     "title": "Total Milliseconds by op type sent to storage volumes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(hammerspace_nfs_protocol_ops_to_storage_volumes_nanosec{instance=~\"$node\",job=~\"$job\",servicer=\"protocol\"}[1m]) / 1000000",
       "legendFormat": "{{servicer}} {{op}}"
      }
     ]
    }
   ]
  }
 ]
}