apiVersion: 1

providers:
  - name: 'hammerspace-dashboards'
    folder: '' 
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    options:
      path: /etc/grafana/provisioning/dashboards/json


